In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use(['seaborn-whitegrid'])

# 텐서(Tensor)

### 일반적으로 텐서는 3차원 이상을 다룰 때 표현하는 방식이지만,
### 여기서는 어떠한 데이터를 표현할 대, 그 값 모두를 텐서라고 부르기로 함

In [3]:
a = np.array([1, 2])
b = np.array([[1, 2],
            [3, 4]])
c = np.array([10])
d = np.array(3)

### a, b, c, d 모두 텐서라고 지칭할 수 있음

### - 랭크(rank): 텐서의 축을 나타내고, 넘파이(numpy)의 ndim으로 구할 수 있음

In [8]:
a = np.array([1, 2])
a.ndim

1

In [11]:
b = np.array([[1, 2], [3, 4]])
b.ndim

2

In [12]:
d = np.array(3)
d.ndim

0

# 스칼라(0차원 텐서)
### - 하나의 숫자를 담고 있는 텐서
### - 형상은 없음

In [14]:
x = np.array(3)
print(x)
print(x.shape)
print(np.ndim(x))

3
()
0


# 벡터(1차원 텐서)
### - 숫자의 배열을 나타내는 텐서

In [15]:
x = np.array([1, 2, 3, 4])
print(x)
print(x.shape)
print(np.ndim(x))

[1 2 3 4]
(4,)
1


# 벡터의 합
### - 같은 형상(shape)일 때, 각 원소별로 계산

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = a + b

print(c)
print(c.shape)
print(np.ndim(c))

[ 6  8 10 12]
(4,)
1


# 벡터의 곱
## A = (x1, x2, x3, ..., xn), B = (y1, y2, y3,...,yn) 일 때
### 원소곱
### - 같은 형상(shape)일 대, 각 원소별로 계산
### A X B  = (x1y1, x2y2, x3y3,...,xnyn)
### 벡터곱 (product, dot)
### - 두 1차원 벡터가 있을 때 각각의 성분끼리의 곱을 모두 더하는 계산
### A X B(transpose) = (x1y1 + x2y2 + x3y3 + ... + xnyn)

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = a * b
print(c)
print(c.shape)
print(np.ndim(c))
print("-----------------------")

x = np.array([1, 2, 0])
y = np.array([0, 2, 1])
z = np.dot(x, y)
print(z)
print(z.shape)
print(np.ndim(z))

[ 5 12 21 32]
(4,)
1
-----------------------
4
()
0


# 스칼라와 벡터의 곱

In [18]:
a = np.array(10)
b = np.array([1, 2, 3])
print(a * b)

[10 20 30]


# 2차원 텐서(행렬)
### - 2차원 텐서는 행렬로 생각할 수 있음
#### (m, n) 형상의 배열

In [22]:
matrix = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(matrix)
print(matrix.shape)
print(np.ndim(matrix))
print("----------------")
matrix2 = np.array([[1, 2, 3, 4]])
print(matrix2)
print(matrix2.shape)
print(np.ndim(matrix2))

[[1 2 3]
 [4 5 6]]
(2, 3)
2
----------------
[[1 2 3 4]]
(1, 4)
2


# 행렬 원소곱
### - 같은 형상(shape)일 때 덧셈, 곱셈과 같은 연산은 원소별로 진행

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 10], [10, 10]])

print("행렬 A\n", A)
print("행렬 B\n", B)
print("A * B\n", A * B)

행렬 A
 [[1 2]
 [3 4]]
행렬 B
 [[10 10]
 [10 10]]
A * B
 [[10 20]
 [30 40]]


# 행렬 점곱(내적, product)
### - 1차원 벡터와 마찬가지로 앞 행렬의 열과 뒤 행렬의 행의 수가 같아야 함

In [25]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[2, 3, 4], [2, 3, 4]])
print("행렬 M\n", M)
print("행렬 N\n", N)
L = np.dot(M, N)
print("행렬 L\n", L)
print(L.shape)
print(np.ndim(L))

행렬 M
 [[1 2]
 [3 4]]
행렬 N
 [[2 3 4]
 [2 3 4]]
행렬 L
 [[ 6  9 12]
 [14 21 28]]
(2, 3)
2


In [26]:
m = np.array([[1], [2], [3]]) # 3 X 1 행렬
n = np.array([[1], [2], [3]]) # 3 X 1 행렬

l = np.dot(m, n) # 에러 발생

print(l)
print(l.shape)
print(np.ndim(l))

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

# 역행렬
### - 어떤 A가 있을 때, 곱해서 단위행렬(E)를 만드는 행렬 B가 존재한다면, 행렬 B는 A의 역행렬

In [29]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.linalg.inv(A) # np.linalg.inv(행렬): 역행렬 구하기
print(B)

print(np.dot(A, B))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [31]:
B = np.array([[3, 3], [2, 2]]) # B 행렬 자체가 역행렬이 없음
print(np.linalg.inv(B)) # 에러 발생

LinAlgError: Singular matrix

# 전치행렬
### - 행과 열을 바꾼 배열의 형태

In [33]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('A\n', A)
print('A.shape\n', A.shape)
print("-------------")
A_ = A.T # A.T: A의 전치행렬
print('A의 전치행렬\n', A_)
print('(A.T).shape\n', A_.shape)

B = A_.T # 전치행렬을 다시 전치행렬
print(B)

A
 [[1 2 3]
 [4 5 6]]
A.shape
 (2, 3)
-------------
A의 전치행렬
 [[1 4]
 [2 5]
 [3 6]]
(A.T).shape
 (3, 2)
[[1 2 3]
 [4 5 6]]


# 3차원 텐서
### 보통 이미지를 나타낼 때 사용되는 텐서
#### - (width, height, (color)channels)
#### - 일반적으로 Numpy array로 표현

### 시계열 데이터 또는 시퀀스(sequence) 데이터를 표현할 때도 사용
#### - (samples, timesteps, features)
#### - (예시) 주식 가격 데이터셋, 시간에 따른 질병 발병 건수

In [36]:
X = np.array([[[5, 3, 2, 1],
              [5, 5, 3, 1],
              [6, 1, 2, 3]],
             [[1, 1, 1, 1],
             [3, 4, 7, 5],
             [1, 8, 3, 4]],
             [[10, 9, 3, 9],
             [5, 4, 3, 2],
             [7, 6, 3, 4]]]) # 3 X 3 X 4

print('X\n', X, end = '\n\n')
print('X.shape:', X.shape)
print('X.ndim:', X.ndim)

X
 [[[ 5  3  2  1]
  [ 5  5  3  1]
  [ 6  1  2  3]]

 [[ 1  1  1  1]
  [ 3  4  7  5]
  [ 1  8  3  4]]

 [[10  9  3  9]
  [ 5  4  3  2]
  [ 7  6  3  4]]]

X.shape: (3, 3, 4)
X.ndim: 3


In [39]:
B = np.array([[[2, 3, 4], [2, 3, 4]],
              [[1, 1, 1], [1, 1, 1]]])

print('행렬 B\n', B, end = '\n\n')
print('B.shape\n', B.shape, end = '\n\n')
print('B.ndim\n', B.ndim, end = '\n\n')
print('B의 전치행렬\n', B.T) # 3차원 텐서도 transpose 가능

행렬 B
 [[[2 3 4]
  [2 3 4]]

 [[1 1 1]
  [1 1 1]]]

B.shape
 (2, 2, 3)

B.ndim
 3

B의 전치행렬
 [[[2 1]
  [2 1]]

 [[3 1]
  [3 1]]

 [[4 1]
  [4 1]]]


In [2]:
from IPython.display import Image

# 3차원 텐서 활용 예시(이미지)
### MNIST Dataset
#### - 28x28 사이즈의 gray scale 이미지들로 구성
![MNIST](image/MNIST.png)
#### - gray scale: 0~255의 값을 통해 밝기를 표현
#### - 0으로 갈수록 어두워지고, 255로 갈수록 밝아짐
![grayscale](image/grayscale.jpeg)

In [9]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

In [11]:
print(train_images.ndim)    

NameError: name 'train_images' is not defined

In [ ]:
print(train_images.shape)

In [ ]:
temp_image = train_images[3]
plt.imshow(temp_image, cmap = 'gray')
plt.show()

# 브로드캐스팅(broadcasting)
### - 넘파이에서 다른 형상(shape)끼리 계산 가능

In [13]:
a = np.array(10)
b = np.array([10, 20, 30])
print(np.dot(a, b))
print(a * b)

[100 200 300]
[100 200 300]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print('행렬 A\n', A)
print('행렬 B\n', B)
print('A * B\n', A * B) # broadcasting 된 결과 출력

행렬 A
 [[1 2]
 [3 4]]
행렬 B
 [10 20]
A * B
 [[10 40]
 [30 80]]


In [16]:
A = np.array([[[1, 1, 1],
             [2, 2, 2]],
              [[3, 3, 3],
              [4, 4, 4]]])
B = np.array([[1, 10, 10]])

print('행렬 A\n', A)
print('A.shape:', A.shape)
print('행렬 B\n', B)
print('B.shape:', B.shape)
print('A * B\n', A * B)

행렬 A
 [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
A.shape: (2, 2, 3)
행렬 B
 [[ 1 10 10]]
B.shape: (1, 3)
A * B
 [[[ 1 10 10]
  [ 2 20 20]]

 [[ 3 30 30]
  [ 4 40 40]]]


In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]]) # 2 X 3
B = np.array([10, 10]) # 2
# Broadcasting 안되는 예시
print(A * B)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

# 5차원 텐서
### - Color Image Datasets(4차원)
#### - (samples, height, width, channels) (Keras, Tensorflow)
#### - (samples, chaneels, height, width) (Pytorch)

### 동영상 (5차원)
#### 1. (samples, frames, height, width, channels)
#### 2. (samples, frames, channels, height, width)
#### - 예시 1) (4, 300, 1920, 1080, 3)
####            1920 X 1080 사이즈 3채널의 300프레임 수를 가진 배치가 4개

# 텐서 크기 변환
### - reshape로 텐서의 크기 변환 가능
### - 변환 전의 원소의 개수와 변환 이후의 텐서의 개수가 같아야 함

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print('행렬 A\n', A)
print('A.shape:', A.shape)
print('-------------')

A = A.reshape(6)
print('행렬 A\n', A)
print('A.shape:', A.shape)

## 2차원을 1차원으로 변환

행렬 A
 [[1 2 3]
 [4 5 6]]
A.shape: (2, 3)
-------------
행렬 A
 [1 2 3 4 5 6]
A.shape: (6,)


In [16]:
B = np.array([[[2, 3, 4], [2, 3, 4]],
            [[1, 1, 1], [1, 1, 1]]])

print('행렬 B\n', B)
print('B.shape:', B.shape)
print("----------------")

B = B.reshape(3, 4)
print('행렬 B\n', B)
print('B.shape:', B.shape)
# 3차원 텐서를 2차원 텐서로 변환

행렬 B
 [[[2 3 4]
  [2 3 4]]

 [[1 1 1]
  [1 1 1]]]
B.shape: (2, 2, 3)
----------------
행렬 B
 [[2 3 4 2]
 [3 4 1 1]
 [1 1 1 1]]
B.shape: (3, 4)


### -1 을 통해 자동으로 형상을 지정 가능
### 원소의 갯수에 맞게 넘파이가 자동으로 형상을 지정

### ex)
### (2, 2, 3) -> (3, -1) (O) (3, 4) 로 자동 지정
### (2, 2, 3) -> (2, 1, 6) (O)
### (2, 2, 3) -> (2, -1, -1) (X)
### (2, 2, 3) -> (2, 5, -1) (X)

In [18]:
B = np.array([[[2, 3, 4], [2, 3, 4]],
            [[1, 1, 1], [1, 1, 1]]])

print('행렬 B\n', B)
print('B.shape:', B.shape)
print("----------------")

B = B.reshape(4, -1)
print('행렬 B\n', B)
print('B.shape:', B.shape)

행렬 B
 [[[2 3 4]
  [2 3 4]]

 [[1 1 1]
  [1 1 1]]]
B.shape: (2, 2, 3)
----------------
행렬 B
 [[2 3 4]
 [2 3 4]
 [1 1 1]
 [1 1 1]]
B.shape: (4, 3)
